name: 'Terraform VNet Hub Prod'

on:
  push:
    branches:
    - 'main'
    paths:
    - .github/workflows/vnet_hub_prod.yml
    - live/vnet_hub/prod_eastus2/*
    - live/vnet_hub/prod_centralus/*
    - modules/vnet_hub/*

jobs:
  vnet-hub-prod-eastus2-call-workflow-terraform-deploy:
    if: github.ref == 'refs/heads/main'
    name: 'Terraform - Vnet hub - prod eastus2'
    uses: ./.github/workflows/workflow_terraform_plan_apply.yml
    with:
      stageNameSuffix:  vnet_hub_prod_eastus2
      environment: prod
      workingDirectory:  ./live/vnet_hub/prod_eastus2
    secrets: inherit

  vnet-hub-prod-centralus-call-workflow-terraform-deploy:
    if: github.ref == 'refs/heads/main'
    name: 'Terraform - Vnet hub - prod centralus'
    uses: ./.github/workflows/workflow_terraform_plan_apply.yml
    with:
      stageNameSuffix:  vnet_hub_prod_centralus
      environment: prod
      workingDirectory:  ./live/vnet_hub/prod_centralus
    secrets: inherit
    needs: [vnet-hub-prod-eastus2-call-workflow-terraform-deploy]